### ISSUE TITLE
Sorry, i can't find the tang9k directory, is this exist?

### ISSUE THREAD

**Issue by Mozes-Y** [LoveLonelyTime/LLTRISC-V#1]
![image](https://github.com/LoveLonelyTime/LLTRISC-V/assets/71743086/3822ad31-e663-4251-b1e6-cca9e7c6bf28)

**Comment by LoveLonelyTime** [comment]
I almost forgot about it. Thank u, I will update it.

**Comment by Mozes-Y** [comment]
> I almost forgot about it. Thank u, I will update it.

OK, thanks!

**Comment by LoveLonelyTime** [comment]
Updated.
